-- ===========================================================================
-- SETTINGS REFERENCE DATA - generated, do not edit by hand
-- ===========================================================================
-- Generated by scripts/build-settings-seed.js from the InventoryDB database.
-- Applied by db-server/scripts/7-seed-settings.ps1.
--
-- Contents: the lookup/configuration tables behind the /settings pages. NOT
-- transactional data - a new installation starts with no items or shipments.
--
-- Tables are ordered by FOREIGN KEY dependency, not alphabetically, so this
-- file loads top to bottom without deferring constraints.
--
-- Row counts at generation time:
--   customers                3
--   item_types               3
--   sources                  2
--   item_status              5
--   test_station_status      3
--   test_stations_type       2
--   photo_types              4
--   holiday_types            3
--   weekday_defaults         7
--   workday_overrides        0
--   reference_items          1
--   test_stations            5
--   testing_routes           4
--   department_holidays      0
--   reference_item_images    0
--
-- (no reference-item images)
-- ===========================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- customers  (3 rows)
-- ---------------------------------------------------------------------------
INSERT INTO public.customers (id, name, customer_code) VALUES (3, 'מנדי                                              ', '1') ON CONFLICT DO NOTHING;
INSERT INTO public.customers (id, name, customer_code) VALUES (2, 'מנשה                                              ', '12') ON CONFLICT DO NOTHING;
INSERT INTO public.customers (id, name, customer_code) VALUES (4, 'ירוחם                                             ', '565') ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- item_types  (3 rows)
-- ---------------------------------------------------------------------------
INSERT INTO public.item_types (item_type_id, item_type_desc) VALUES (1, 'מחשב                                              ') ON CONFLICT DO NOTHING;
INSERT INTO public.item_types (item_type_id, item_type_desc) VALUES (2, 'עכבר                                              ') ON CONFLICT DO NOTHING;
INSERT INTO public.item_types (item_type_id, item_type_desc) VALUES (3, 'מקלדת                                             ') ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- sources  (2 rows)
-- ---------------------------------------------------------------------------
INSERT INTO public.sources (source_id, source_desc) VALUES (1, 'מחסן חיצוני') ON CONFLICT DO NOTHING;
INSERT INTO public.sources (source_id, source_desc) VALUES (3, 'מחסן פנימי') ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- item_status  (5 rows)
-- ---------------------------------------------------------------------------
INSERT INTO public.item_status (item_status_id, item_status_desc) VALUES (1, 'בדיקה                                             ') ON CONFLICT DO NOTHING;
INSERT INTO public.item_status (item_status_id, item_status_desc) VALUES (2, 'המתנה                                             ') ON CONFLICT DO NOTHING;
INSERT INTO public.item_status (item_status_id, item_status_desc) VALUES (3, 'סיים                                              ') ON CONFLICT DO NOTHING;
INSERT INTO public.item_status (item_status_id, item_status_desc) VALUES (4, 'ממתין למחקר                                       ') ON CONFLICT DO NOTHING;
INSERT INTO public.item_status (item_status_id, item_status_desc) VALUES (5, 'במחקר                                             ') ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- test_station_status  (3 rows)
-- ---------------------------------------------------------------------------
INSERT INTO public.test_station_status (test_station_status_id, test_station_status_desc) VALUES (1, 'עבודה                                             ') ON CONFLICT DO NOTHING;
INSERT INTO public.test_station_status (test_station_status_id, test_station_status_desc) VALUES (2, 'המתנה                                             ') ON CONFLICT DO NOTHING;
INSERT INTO public.test_station_status (test_station_status_id, test_station_status_desc) VALUES (3, 'לא פעילה                                          ') ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- test_stations_type  (2 rows)
-- ---------------------------------------------------------------------------
INSERT INTO public.test_stations_type (test_station_type_id, test_type_desc, parents_only) VALUES (1, 'חשמל                                              ', false) ON CONFLICT DO NOTHING;
INSERT INTO public.test_stations_type (test_station_type_id, test_type_desc, parents_only) VALUES (2, 'מכניקה                                            ', false) ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- photo_types  (4 rows)
-- ---------------------------------------------------------------------------
INSERT INTO public.photo_types (photo_type_id, code, photo_type_desc, sort_order, is_active, created_at) VALUES (1, 'package', 'צילום אריזה', 1, true, '2026-08-14 10:00:00.771947+00') ON CONFLICT DO NOTHING;
INSERT INTO public.photo_types (photo_type_id, code, photo_type_desc, sort_order, is_active, created_at) VALUES (2, 'product', 'צילום פריט', 2, true, '2026-08-14 10:00:00.771947+00') ON CONFLICT DO NOTHING;
INSERT INTO public.photo_types (photo_type_id, code, photo_type_desc, sort_order, is_active, created_at) VALUES (3, 'disassembly', 'צילום פירוק', 3, true, '2026-08-14 10:00:00.771947+00') ON CONFLICT DO NOTHING;
INSERT INTO public.photo_types (photo_type_id, code, photo_type_desc, sort_order, is_active, created_at) VALUES (4, 'assembly', 'צילום הרכבה', 4, false, '2026-08-14 10:00:00.771947+00') ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- holiday_types  (3 rows)
-- ---------------------------------------------------------------------------
INSERT INTO public.holiday_types (id, name, is_system, created_at) VALUES (1, 'חופשה מרוכזת', true, '2026-08-14 10:00:00.771947+00') ON CONFLICT DO NOTHING;
INSERT INTO public.holiday_types (id, name, is_system, created_at) VALUES (2, 'יום גיבוש', true, '2026-08-14 10:00:00.771947+00') ON CONFLICT DO NOTHING;
INSERT INTO public.holiday_types (id, name, is_system, created_at) VALUES (3, 'השבתה', true, '2026-08-14 10:00:00.771947+00') ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- weekday_defaults  (7 rows)
-- ---------------------------------------------------------------------------
INSERT INTO public.weekday_defaults (weekday, is_working, start_time, end_time, break_start, break_end, updated_by, updated_at) VALUES (0, true, '07:00', '15:35', '12:00', '13:00', NULL, '2026-08-14 10:00:00.771947+00') ON CONFLICT DO NOTHING;
INSERT INTO public.weekday_defaults (weekday, is_working, start_time, end_time, break_start, break_end, updated_by, updated_at) VALUES (1, true, '07:00', '15:35', '12:00', '13:00', NULL, '2026-08-14 10:00:00.771947+00') ON CONFLICT DO NOTHING;
INSERT INTO public.weekday_defaults (weekday, is_working, start_time, end_time, break_start, break_end, updated_by, updated_at) VALUES (2, true, '07:00', '15:35', '12:00', '13:00', NULL, '2026-08-14 10:00:00.771947+00') ON CONFLICT DO NOTHING;
INSERT INTO public.weekday_defaults (weekday, is_working, start_time, end_time, break_start, break_end, updated_by, updated_at) VALUES (3, true, '07:00', '15:35', '12:00', '13:00', NULL, '2026-08-14 10:00:00.771947+00') ON CONFLICT DO NOTHING;
INSERT INTO public.weekday_defaults (weekday, is_working, start_time, end_time, break_start, break_end, updated_by, updated_at) VALUES (4, true, '07:00', '15:35', '12:00', '13:00', NULL, '2026-08-14 10:00:00.771947+00') ON CONFLICT DO NOTHING;
INSERT INTO public.weekday_defaults (weekday, is_working, start_time, end_time, break_start, break_end, updated_by, updated_at) VALUES (5, false, NULL, NULL, NULL, NULL, NULL, '2026-08-14 10:00:00.771947+00') ON CONFLICT DO NOTHING;
INSERT INTO public.weekday_defaults (weekday, is_working, start_time, end_time, break_start, break_end, updated_by, updated_at) VALUES (6, false, NULL, NULL, NULL, NULL, NULL, '2026-08-14 10:00:00.771947+00') ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- workday_overrides  (0 rows)
-- ---------------------------------------------------------------------------
-- (no rows)

-- ---------------------------------------------------------------------------
-- reference_items  (1 row)
-- ---------------------------------------------------------------------------
INSERT INTO public.reference_items (reference_item_id, item_type_id, manufacturer_sku, manufacturer, name, reference_weight, notes, primary_image_id, created_at, updated_at) VALUES (1, 1, '6512336', 'DF-HHB', 'צמ', '0.5', NULL, NULL, '2026-08-16 06:08:40.447+00', '2026-08-16 06:09:07.764+00') ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- test_stations  (5 rows)
-- ---------------------------------------------------------------------------
INSERT INTO public.test_stations (test_station_id, test_station_type_id, test_station_desc, status, is_research) VALUES (4, 2, 'עגכ                                               ', 2, false) ON CONFLICT DO NOTHING;
INSERT INTO public.test_stations (test_station_id, test_station_type_id, test_station_desc, status, is_research) VALUES (5, 2, 'גה                                                ', 3, false) ON CONFLICT DO NOTHING;
INSERT INTO public.test_stations (test_station_id, test_station_type_id, test_station_desc, status, is_research) VALUES (2, 1, 'להמתין                                            ', 2, false) ON CONFLICT DO NOTHING;
INSERT INTO public.test_stations (test_station_id, test_station_type_id, test_station_desc, status, is_research) VALUES (1, 1, 'ססס                                               ', 2, false) ON CONFLICT DO NOTHING;
INSERT INTO public.test_stations (test_station_id, test_station_type_id, test_station_desc, status, is_research) VALUES (3, 2, 'dsd                                               ', 2, false) ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- testing_routes  (4 rows)
-- ---------------------------------------------------------------------------
INSERT INTO public.testing_routes (test_route_id, item_type_id, test_station_type_id, route_steps, route_number) VALUES (1, 1, 1, '{1,2,1}', 1) ON CONFLICT DO NOTHING;
INSERT INTO public.testing_routes (test_route_id, item_type_id, test_station_type_id, route_steps, route_number) VALUES (2, 1, 1, '{2,1,2}', 2) ON CONFLICT DO NOTHING;
INSERT INTO public.testing_routes (test_route_id, item_type_id, test_station_type_id, route_steps, route_number) VALUES (3, 2, 2, '{2,2}', 2) ON CONFLICT DO NOTHING;
INSERT INTO public.testing_routes (test_route_id, item_type_id, test_station_type_id, route_steps, route_number) VALUES (4, 2, 1, '{1,2,2,1}', 1) ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- department_holidays  (0 rows)
-- ---------------------------------------------------------------------------
-- (no rows)

-- ---------------------------------------------------------------------------
-- reference_item_images  (0 rows)
-- ---------------------------------------------------------------------------
-- (no rows)


-- ---------------------------------------------------------------------------
-- Sequence reset
-- ---------------------------------------------------------------------------
-- The rows above carry explicit ids while the sequences behind those columns
-- are still at 1. Without this, the first record a user creates in the UI
-- collides with a seeded id and fails on a duplicate key.
DO $seq$
BEGIN
    PERFORM setval(pg_get_serial_sequence('public."customers"', 'id'), COALESCE((SELECT MAX("id") FROM public."customers"), 0) + 1, false);
    PERFORM setval(pg_get_serial_sequence('public."item_types"', 'item_type_id'), COALESCE((SELECT MAX("item_type_id") FROM public."item_types"), 0) + 1, false);
    PERFORM setval(pg_get_serial_sequence('public."sources"', 'source_id'), COALESCE((SELECT MAX("source_id") FROM public."sources"), 0) + 1, false);
    PERFORM setval(pg_get_serial_sequence('public."item_status"', 'item_status_id'), COALESCE((SELECT MAX("item_status_id") FROM public."item_status"), 0) + 1, false);
    PERFORM setval(pg_get_serial_sequence('public."test_station_status"', 'test_station_status_id'), COALESCE((SELECT MAX("test_station_status_id") FROM public."test_station_status"), 0) + 1, false);
    PERFORM setval(pg_get_serial_sequence('public."test_stations_type"', 'test_station_type_id'), COALESCE((SELECT MAX("test_station_type_id") FROM public."test_stations_type"), 0) + 1, false);
    PERFORM setval(pg_get_serial_sequence('public."photo_types"', 'photo_type_id'), COALESCE((SELECT MAX("photo_type_id") FROM public."photo_types"), 0) + 1, false);
    PERFORM setval(pg_get_serial_sequence('public."holiday_types"', 'id'), COALESCE((SELECT MAX("id") FROM public."holiday_types"), 0) + 1, false);
    PERFORM setval(pg_get_serial_sequence('public."workday_overrides"', 'id'), COALESCE((SELECT MAX("id") FROM public."workday_overrides"), 0) + 1, false);
    PERFORM setval(pg_get_serial_sequence('public."reference_items"', 'reference_item_id'), COALESCE((SELECT MAX("reference_item_id") FROM public."reference_items"), 0) + 1, false);
    PERFORM setval(pg_get_serial_sequence('public."test_stations"', 'test_station_id'), COALESCE((SELECT MAX("test_station_id") FROM public."test_stations"), 0) + 1, false);
    PERFORM setval(pg_get_serial_sequence('public."testing_routes"', 'test_route_id'), COALESCE((SELECT MAX("test_route_id") FROM public."testing_routes"), 0) + 1, false);
    PERFORM setval(pg_get_serial_sequence('public."department_holidays"', 'id'), COALESCE((SELECT MAX("id") FROM public."department_holidays"), 0) + 1, false);
    PERFORM setval(pg_get_serial_sequence('public."reference_item_images"', 'reference_item_image_id'), COALESCE((SELECT MAX("reference_item_image_id") FROM public."reference_item_images"), 0) + 1, false);
END
$seq$;

COMMIT;
