-- ===========================================================================
-- APPLICATION SCHEMA — generated, do not edit by hand
-- ===========================================================================
-- Generated by scripts/build-airgap-schema.js from prisma/migrations/.
-- Applied automatically by the postgres container on a FRESH data volume.
--
-- To apply it to an EXISTING database instead, run this whole file in DBeaver
-- against the application database. It is NOT idempotent — run it once, on an
-- empty database.
--
-- Migrations included (17):
--   0_init
--   20260217140614_add_poc_and_stokekeeper
--   20260218000000_dashboard_optimization
--   20260224085257_update_database_structure
--   20260528000000_add_file_objects
--   20260604000000_add_updated_by_to_file_objects
--   20260709084717_add_reference_items
--   20260712085744_add_reference_weight
--   20260712124950_add_test_results
--   20260713131814_add_settings_unique_constraints
--   20260719000000_add_photo_types
--   20260719120000_add_disassembly_assembly_photo_types
--   20260720100000_add_station_type_parents_only
--   20260727120000_add_work_hours
--   20260816103131_add_worker_name_snapshots
--   20260816103434_drop_local_workers_table
--   20260816114251_makat_to_text
-- ===========================================================================


-- ---------------------------------------------------------------------------
-- migration: 0_init
-- ---------------------------------------------------------------------------
-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateTable
CREATE TABLE "customer_snapshots" (
    "snapshot_date" DATE NOT NULL,
    "customer_id" INTEGER NOT NULL,
    "customer_code" VARCHAR(255),
    "customer_name" VARCHAR(255),
    "total_items" INTEGER NOT NULL DEFAULT 0,
    "items_in_queue" INTEGER NOT NULL DEFAULT 0,
    "items_in_test" INTEGER NOT NULL DEFAULT 0,
    "items_waiting_for_research" INTEGER NOT NULL DEFAULT 0,
    "items_in_research" INTEGER NOT NULL DEFAULT 0,
    "finished_items" INTEGER NOT NULL DEFAULT 0,
    "items_in_routes" INTEGER NOT NULL DEFAULT 0,
    "success_percentage" DECIMAL(5,2) NOT NULL DEFAULT 0,
    "items_in_routes_percentage" DECIMAL(5,2) NOT NULL DEFAULT 0,
    "average_time_minutes" DECIMAL(10,2),
    "created_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "customer_snapshots_pkey" PRIMARY KEY ("snapshot_date","customer_id")
);

-- CreateTable
CREATE TABLE "customer_snapshots_daily" (
    "snapshot_id" SERIAL NOT NULL,
    "customer_id" INTEGER NOT NULL,
    "snapshot_date" DATE NOT NULL,
    "total_items" INTEGER DEFAULT 0,
    "items_in_queue" INTEGER DEFAULT 0,
    "items_in_test" INTEGER DEFAULT 0,
    "items_finished" INTEGER DEFAULT 0,
    "items_waiting_for_research" INTEGER DEFAULT 0,
    "items_in_research" INTEGER DEFAULT 0,
    "items_in_routes" INTEGER DEFAULT 0,
    "total_processed_in_period" INTEGER DEFAULT 0,
    "created_at" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "customer_snapshots_daily_pkey" PRIMARY KEY ("snapshot_id")
);

-- CreateTable
CREATE TABLE "customer_snapshots_monthly" (
    "snapshot_date" DATE NOT NULL,
    "customer_id" INTEGER NOT NULL,
    "customer_code" VARCHAR(255),
    "customer_name" VARCHAR(255),
    "total_items" INTEGER NOT NULL DEFAULT 0,
    "items_in_queue" INTEGER NOT NULL DEFAULT 0,
    "items_in_test" INTEGER NOT NULL DEFAULT 0,
    "items_waiting_for_research" INTEGER NOT NULL DEFAULT 0,
    "items_in_research" INTEGER NOT NULL DEFAULT 0,
    "finished_items" INTEGER NOT NULL DEFAULT 0,
    "items_in_routes" INTEGER NOT NULL DEFAULT 0,
    "success_percentage" DECIMAL(5,2) NOT NULL DEFAULT 0,
    "items_in_routes_percentage" DECIMAL(5,2) NOT NULL DEFAULT 0,
    "average_time_minutes" DECIMAL(10,2),
    "created_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "customer_snapshots_monthly_pkey" PRIMARY KEY ("snapshot_date","customer_id")
);

-- CreateTable
CREATE TABLE "customer_snapshots_quarterly" (
    "snapshot_date" DATE NOT NULL,
    "customer_id" INTEGER NOT NULL,
    "customer_code" VARCHAR(255),
    "customer_name" VARCHAR(255),
    "total_items" INTEGER NOT NULL DEFAULT 0,
    "items_in_queue" INTEGER NOT NULL DEFAULT 0,
    "items_in_test" INTEGER NOT NULL DEFAULT 0,
    "items_waiting_for_research" INTEGER NOT NULL DEFAULT 0,
    "items_in_research" INTEGER NOT NULL DEFAULT 0,
    "finished_items" INTEGER NOT NULL DEFAULT 0,
    "items_in_routes" INTEGER NOT NULL DEFAULT 0,
    "success_percentage" DECIMAL(5,2) NOT NULL DEFAULT 0,
    "items_in_routes_percentage" DECIMAL(5,2) NOT NULL DEFAULT 0,
    "average_time_minutes" DECIMAL(10,2),
    "created_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "customer_snapshots_quarterly_pkey" PRIMARY KEY ("snapshot_date","customer_id")
);

-- CreateTable
CREATE TABLE "customers" (
    "id" SERIAL NOT NULL,
    "name" CHAR(50) NOT NULL,
    "customer_code" VARCHAR(100) NOT NULL,

    CONSTRAINT "customers_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "daily_counters" (
    "date_key" DATE NOT NULL,
    "counter" INTEGER DEFAULT 0,

    CONSTRAINT "daily_counters_pkey" PRIMARY KEY ("date_key")
);

-- CreateTable
CREATE TABLE "finished_item" (
    "item_id" SERIAL NOT NULL,
    "item_type_id" INTEGER NOT NULL,
    "current_status" INTEGER NOT NULL,
    "current_route_step" INTEGER NOT NULL,
    "test_station_id" INTEGER,
    "created_at" TIMESTAMP(6) NOT NULL,
    "finished_at" TIMESTAMP(6),
    "is_finished" BOOLEAN NOT NULL DEFAULT false,
    "processing_start_time" TIMESTAMP(6),
    "q_start_time" TIMESTAMP(6),

    CONSTRAINT "finished_item_pkey" PRIMARY KEY ("item_id")
);

-- CreateTable
CREATE TABLE "item_route_history" (
    "log_id" SERIAL NOT NULL,
    "item_id" BIGINT NOT NULL,
    "test_station_id" INTEGER NOT NULL,
    "current_route_step" INTEGER NOT NULL,
    "queue_start_time" TIMESTAMP(6),
    "processing_start_time" TIMESTAMP(6),
    "processing_end_time" TIMESTAMP(6),
    "worker_id" INTEGER,
    "route_number" INTEGER NOT NULL DEFAULT 1,

    CONSTRAINT "item_route_history_pkey" PRIMARY KEY ("log_id")
);

-- CreateTable
CREATE TABLE "item_routes" (
    "item_id" BIGSERIAL NOT NULL,
    "item_type_id" INTEGER NOT NULL,
    "current_status" INTEGER NOT NULL,
    "current_route_step" INTEGER NOT NULL,
    "test_station_id" INTEGER,
    "created_at" TIMESTAMP(6) NOT NULL,
    "finished_at" TIMESTAMP(6),
    "is_finished" BOOLEAN NOT NULL DEFAULT false,
    "queue_start_time" TIMESTAMP(6) NOT NULL,
    "processing_start_time" TIMESTAMP(6),
    "route_number" INTEGER NOT NULL DEFAULT 1,

    CONSTRAINT "item_routes_pkey" PRIMARY KEY ("item_id")
);

-- CreateTable
CREATE TABLE "item_status" (
    "item_status_id" SERIAL NOT NULL,
    "item_status_desc" CHAR(50) NOT NULL,

    CONSTRAINT "item_status_pkey" PRIMARY KEY ("item_status_id")
);

-- CreateTable
CREATE TABLE "item_type_snapshots" (
    "snapshot_date" DATE NOT NULL,
    "item_type_id" INTEGER NOT NULL,
    "item_type_desc" VARCHAR(255),
    "total_items" INTEGER NOT NULL DEFAULT 0,
    "items_in_queue" INTEGER NOT NULL DEFAULT 0,
    "items_in_test" INTEGER NOT NULL DEFAULT 0,
    "items_waiting_for_research" INTEGER NOT NULL DEFAULT 0,
    "items_in_research" INTEGER NOT NULL DEFAULT 0,
    "items_finished" INTEGER NOT NULL DEFAULT 0,
    "items_in_routes" INTEGER NOT NULL DEFAULT 0,
    "completion_percentage" DECIMAL(5,2) NOT NULL DEFAULT 0,
    "items_in_routes_percentage" DECIMAL(5,2) NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "item_type_snapshots_pkey" PRIMARY KEY ("snapshot_date","item_type_id")
);

-- CreateTable
CREATE TABLE "item_type_snapshots_monthly" (
    "snapshot_date" DATE NOT NULL,
    "item_type_id" INTEGER NOT NULL,
    "item_type_desc" VARCHAR(255),
    "total_items" INTEGER NOT NULL DEFAULT 0,
    "items_in_queue" INTEGER NOT NULL DEFAULT 0,
    "items_in_test" INTEGER NOT NULL DEFAULT 0,
    "items_waiting_for_research" INTEGER NOT NULL DEFAULT 0,
    "items_in_research" INTEGER NOT NULL DEFAULT 0,
    "items_finished" INTEGER NOT NULL DEFAULT 0,
    "items_in_routes" INTEGER NOT NULL DEFAULT 0,
    "completion_percentage" DECIMAL(5,2) NOT NULL DEFAULT 0,
    "items_in_routes_percentage" DECIMAL(5,2) NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "item_type_snapshots_monthly_pkey" PRIMARY KEY ("snapshot_date","item_type_id")
);

-- CreateTable
CREATE TABLE "item_type_snapshots_quarterly" (
    "snapshot_date" DATE NOT NULL,
    "item_type_id" INTEGER NOT NULL,
    "item_type_desc" VARCHAR(255),
    "total_items" INTEGER NOT NULL DEFAULT 0,
    "items_in_queue" INTEGER NOT NULL DEFAULT 0,
    "items_in_test" INTEGER NOT NULL DEFAULT 0,
    "items_waiting_for_research" INTEGER NOT NULL DEFAULT 0,
    "items_in_research" INTEGER NOT NULL DEFAULT 0,
    "items_finished" INTEGER NOT NULL DEFAULT 0,
    "items_in_routes" INTEGER NOT NULL DEFAULT 0,
    "completion_percentage" DECIMAL(5,2) NOT NULL DEFAULT 0,
    "items_in_routes_percentage" DECIMAL(5,2) NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "item_type_snapshots_quarterly_pkey" PRIMARY KEY ("snapshot_date","item_type_id")
);

-- CreateTable
CREATE TABLE "item_types" (
    "item_type_id" SERIAL NOT NULL,
    "item_type_desc" CHAR(50) NOT NULL,

    CONSTRAINT "item_types_pkey" PRIMARY KEY ("item_type_id")
);

-- CreateTable
CREATE TABLE "items" (
    "item_id" BIGINT NOT NULL,
    "customer_id" INTEGER NOT NULL,
    "item_type_id" INTEGER NOT NULL,
    "serial_no" INTEGER NOT NULL,
    "makat" INTEGER NOT NULL,
    "model" CHAR(50) NOT NULL,
    "manufacturer_name" CHAR(50) NOT NULL,
    "manufacturer_no" INTEGER NOT NULL,
    "shipment_id" INTEGER NOT NULL,
    "parent_item_id" BIGINT,

    CONSTRAINT "items_pkey" PRIMARY KEY ("item_id")
);

-- CreateTable
CREATE TABLE "kpi_snapshots" (
    "snapshot_date" DATE NOT NULL,
    "average_queue_time_minutes" DECIMAL(10,2),
    "average_processing_time_minutes" DECIMAL(10,2),
    "total_items_processed" INTEGER NOT NULL DEFAULT 0,
    "items_currently_in_queue" INTEGER NOT NULL DEFAULT 0,
    "items_currently_in_test" INTEGER NOT NULL DEFAULT 0,
    "busiest_station_id" INTEGER,
    "busiest_station_name" VARCHAR(255),
    "busiest_station_count" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "kpi_snapshots_pkey" PRIMARY KEY ("snapshot_date")
);

-- CreateTable
CREATE TABLE "kpi_snapshots_monthly" (
    "snapshot_date" DATE NOT NULL,
    "average_queue_time_minutes" DECIMAL(10,2),
    "average_processing_time_minutes" DECIMAL(10,2),
    "total_items_processed" INTEGER NOT NULL DEFAULT 0,
    "items_currently_in_queue" INTEGER NOT NULL DEFAULT 0,
    "items_currently_in_test" INTEGER NOT NULL DEFAULT 0,
    "busiest_station_id" INTEGER,
    "busiest_station_name" VARCHAR(255),
    "busiest_station_count" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "kpi_snapshots_monthly_pkey" PRIMARY KEY ("snapshot_date")
);

-- CreateTable
CREATE TABLE "kpi_snapshots_quarterly" (
    "snapshot_date" DATE NOT NULL,
    "average_queue_time_minutes" DECIMAL(10,2),
    "average_processing_time_minutes" DECIMAL(10,2),
    "total_items_processed" INTEGER NOT NULL DEFAULT 0,
    "items_currently_in_queue" INTEGER NOT NULL DEFAULT 0,
    "items_currently_in_test" INTEGER NOT NULL DEFAULT 0,
    "busiest_station_id" INTEGER,
    "busiest_station_name" VARCHAR(255),
    "busiest_station_count" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "kpi_snapshots_quarterly_pkey" PRIMARY KEY ("snapshot_date")
);

-- CreateTable
CREATE TABLE "research_history" (
    "research_id" SERIAL NOT NULL,
    "item_id" INTEGER NOT NULL,
    "station_id" INTEGER NOT NULL,
    "sent_at" TIMESTAMP(6),
    "return_at" TIMESTAMP(6),
    "result" INTEGER NOT NULL,
    "comments" TEXT,
    "worker_id" INTEGER,

    CONSTRAINT "research_history_pkey" PRIMARY KEY ("research_id")
);

-- CreateTable
CREATE TABLE "shipment_history" (
    "log_id" SERIAL NOT NULL,
    "shipment_id" INTEGER NOT NULL,
    "sent_shipment_code" TEXT NOT NULL,
    "sent_date" TIMESTAMP(6) NOT NULL,
    "sending_worker_id" INTEGER,
    "item_type_id" INTEGER,
    "makat" INTEGER,
    "amount" INTEGER NOT NULL,
    "created_at" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "signature_path" TEXT,

    CONSTRAINT "shipment_history_pkey" PRIMARY KEY ("log_id")
);

-- CreateTable
CREATE TABLE "shipment_items" (
    "id" SERIAL NOT NULL,
    "shipment_id" INTEGER,
    "item_type_id" INTEGER,
    "quantity" INTEGER NOT NULL,
    "created_at" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "makat" INTEGER,

    CONSTRAINT "shipment_items_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "shipment_snapshots" (
    "snapshot_date" DATE NOT NULL,
    "shipment_id" INTEGER NOT NULL,
    "shipment_code" VARCHAR(255),
    "shipment_date" DATE,
    "customer_id" INTEGER,
    "customer_code" VARCHAR(255),
    "customer_name" VARCHAR(255),
    "total_items" INTEGER NOT NULL DEFAULT 0,
    "items_in_queue" INTEGER NOT NULL DEFAULT 0,
    "items_in_test" INTEGER NOT NULL DEFAULT 0,
    "items_waiting_for_research" INTEGER NOT NULL DEFAULT 0,
    "items_in_research" INTEGER NOT NULL DEFAULT 0,
    "items_finished" INTEGER NOT NULL DEFAULT 0,
    "items_in_routes" INTEGER NOT NULL DEFAULT 0,
    "completion_percentage" DECIMAL(5,2) NOT NULL DEFAULT 0,
    "items_in_routes_percentage" DECIMAL(5,2) NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "shipment_snapshots_pkey" PRIMARY KEY ("snapshot_date","shipment_id")
);

-- CreateTable
CREATE TABLE "shipment_snapshots_monthly" (
    "snapshot_date" DATE NOT NULL,
    "shipment_id" INTEGER NOT NULL,
    "shipment_code" VARCHAR(255),
    "shipment_date" DATE,
    "customer_id" INTEGER,
    "customer_code" VARCHAR(255),
    "customer_name" VARCHAR(255),
    "total_items" INTEGER NOT NULL DEFAULT 0,
    "items_in_queue" INTEGER NOT NULL DEFAULT 0,
    "items_in_test" INTEGER NOT NULL DEFAULT 0,
    "items_waiting_for_research" INTEGER NOT NULL DEFAULT 0,
    "items_in_research" INTEGER NOT NULL DEFAULT 0,
    "items_finished" INTEGER NOT NULL DEFAULT 0,
    "items_in_routes" INTEGER NOT NULL DEFAULT 0,
    "completion_percentage" DECIMAL(5,2) NOT NULL DEFAULT 0,
    "items_in_routes_percentage" DECIMAL(5,2) NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "shipment_snapshots_monthly_pkey" PRIMARY KEY ("snapshot_date","shipment_id")
);

-- CreateTable
CREATE TABLE "shipment_snapshots_quarterly" (
    "snapshot_date" DATE NOT NULL,
    "shipment_id" INTEGER NOT NULL,
    "shipment_code" VARCHAR(255),
    "shipment_date" DATE,
    "customer_id" INTEGER,
    "customer_code" VARCHAR(255),
    "customer_name" VARCHAR(255),
    "total_items" INTEGER NOT NULL DEFAULT 0,
    "items_in_queue" INTEGER NOT NULL DEFAULT 0,
    "items_in_test" INTEGER NOT NULL DEFAULT 0,
    "items_waiting_for_research" INTEGER NOT NULL DEFAULT 0,
    "items_in_research" INTEGER NOT NULL DEFAULT 0,
    "items_finished" INTEGER NOT NULL DEFAULT 0,
    "items_in_routes" INTEGER NOT NULL DEFAULT 0,
    "completion_percentage" DECIMAL(5,2) NOT NULL DEFAULT 0,
    "items_in_routes_percentage" DECIMAL(5,2) NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "shipment_snapshots_quarterly_pkey" PRIMARY KEY ("snapshot_date","shipment_id")
);

-- CreateTable
CREATE TABLE "shipments" (
    "id" SERIAL NOT NULL,
    "shipment_code" VARCHAR(20) NOT NULL,
    "customer_id" INTEGER NOT NULL,
    "shipment_date" TIMESTAMP(6) NOT NULL,
    "makat" INTEGER NOT NULL,
    "amount" INTEGER NOT NULL,
    "shipment_sent_date" TIMESTAMP(6),
    "is_sent" BOOLEAN DEFAULT false,
    "recieving_worker_id" INTEGER,
    "source_id" INTEGER,
    "sending_worker_id" INTEGER,
    "finished_at" TIMESTAMPTZ(6),
    "signature_path" TEXT,

    CONSTRAINT "shipments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "sources" (
    "source_id" SERIAL NOT NULL,
    "source_desc" VARCHAR(100) NOT NULL,

    CONSTRAINT "sources_pkey" PRIMARY KEY ("source_id")
);

-- CreateTable
CREATE TABLE "station_snapshots" (
    "snapshot_date" DATE NOT NULL,
    "station_id" INTEGER NOT NULL,
    "station_name" VARCHAR(255),
    "station_type_name" VARCHAR(255),
    "items_in_queue" INTEGER NOT NULL DEFAULT 0,
    "items_in_test" INTEGER NOT NULL DEFAULT 0,
    "average_current_queue_time_minutes" DECIMAL(10,2),
    "total_processed_in_period" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "station_snapshots_pkey" PRIMARY KEY ("snapshot_date","station_id")
);

-- CreateTable
CREATE TABLE "station_snapshots_monthly" (
    "snapshot_date" DATE NOT NULL,
    "station_id" INTEGER NOT NULL,
    "station_name" VARCHAR(255),
    "station_type_name" VARCHAR(255),
    "items_in_queue" INTEGER NOT NULL DEFAULT 0,
    "items_in_test" INTEGER NOT NULL DEFAULT 0,
    "average_current_queue_time_minutes" DECIMAL(10,2),
    "total_processed_in_period" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "station_snapshots_monthly_pkey" PRIMARY KEY ("snapshot_date","station_id")
);

-- CreateTable
CREATE TABLE "station_snapshots_quarterly" (
    "snapshot_date" DATE NOT NULL,
    "station_id" INTEGER NOT NULL,
    "station_name" VARCHAR(255),
    "station_type_name" VARCHAR(255),
    "items_in_queue" INTEGER NOT NULL DEFAULT 0,
    "items_in_test" INTEGER NOT NULL DEFAULT 0,
    "average_current_queue_time_minutes" DECIMAL(10,2),
    "total_processed_in_period" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "station_snapshots_quarterly_pkey" PRIMARY KEY ("snapshot_date","station_id")
);

-- CreateTable
CREATE TABLE "status_distribution_snapshots" (
    "snapshot_date" DATE NOT NULL,
    "status_id" INTEGER NOT NULL,
    "status_name" VARCHAR(255),
    "count" INTEGER NOT NULL DEFAULT 0,
    "percentage" DECIMAL(5,2) NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "status_distribution_snapshots_pkey" PRIMARY KEY ("snapshot_date","status_id")
);

-- CreateTable
CREATE TABLE "status_distribution_snapshots_monthly" (
    "snapshot_date" DATE NOT NULL,
    "status_id" INTEGER NOT NULL,
    "status_name" VARCHAR(255),
    "count" INTEGER NOT NULL DEFAULT 0,
    "percentage" DECIMAL(5,2) NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "status_distribution_snapshots_monthly_pkey" PRIMARY KEY ("snapshot_date","status_id")
);

-- CreateTable
CREATE TABLE "status_distribution_snapshots_quarterly" (
    "snapshot_date" DATE NOT NULL,
    "status_id" INTEGER NOT NULL,
    "status_name" VARCHAR(255),
    "count" INTEGER NOT NULL DEFAULT 0,
    "percentage" DECIMAL(5,2) NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "status_distribution_snapshots_quarterly_pkey" PRIMARY KEY ("snapshot_date","status_id")
);

-- CreateTable
CREATE TABLE "system_snapshots_daily" (
    "snapshot_id" SERIAL NOT NULL,
    "snapshot_date" DATE NOT NULL,
    "total_items" INTEGER DEFAULT 0,
    "items_in_queue" INTEGER DEFAULT 0,
    "items_in_test" INTEGER DEFAULT 0,
    "items_finished" INTEGER DEFAULT 0,
    "items_waiting_for_research" INTEGER DEFAULT 0,
    "items_in_research" INTEGER DEFAULT 0,
    "items_in_routes" INTEGER DEFAULT 0,
    "created_at" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "system_snapshots_daily_pkey" PRIMARY KEY ("snapshot_id")
);

-- CreateTable
CREATE TABLE "system_snapshots_monthly" (
    "snapshot_id" SERIAL NOT NULL,
    "snapshot_date" DATE NOT NULL,
    "total_items" INTEGER DEFAULT 0,
    "items_in_queue" INTEGER DEFAULT 0,
    "items_in_test" INTEGER DEFAULT 0,
    "items_finished" INTEGER DEFAULT 0,
    "items_waiting_for_research" INTEGER DEFAULT 0,
    "items_in_research" INTEGER DEFAULT 0,
    "items_in_routes" INTEGER DEFAULT 0,
    "created_at" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "system_snapshots_monthly_pkey" PRIMARY KEY ("snapshot_id")
);

-- CreateTable
CREATE TABLE "test_station_status" (
    "test_station_status_id" SERIAL NOT NULL,
    "test_station_status_desc" CHAR(50) NOT NULL,

    CONSTRAINT "test_station_status_pkey" PRIMARY KEY ("test_station_status_id")
);

-- CreateTable
CREATE TABLE "test_stations" (
    "test_station_id" SERIAL NOT NULL,
    "test_station_type_id" INTEGER NOT NULL,
    "test_station_desc" CHAR(50) NOT NULL,
    "status" INTEGER NOT NULL,
    "is_research" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "test_stations_pkey" PRIMARY KEY ("test_station_id")
);

-- CreateTable
CREATE TABLE "test_stations_type" (
    "test_station_type_id" SERIAL NOT NULL,
    "test_type_desc" CHAR(50) NOT NULL,

    CONSTRAINT "test_stations_type_pkey" PRIMARY KEY ("test_station_type_id")
);

-- CreateTable
CREATE TABLE "testing_routes" (
    "test_route_id" SERIAL NOT NULL,
    "item_type_id" INTEGER NOT NULL,
    "test_station_type_id" INTEGER NOT NULL,
    "route_steps" INTEGER[] DEFAULT ARRAY[]::INTEGER[],
    "route_number" INTEGER NOT NULL DEFAULT 1,

    CONSTRAINT "testing_routes_pkey" PRIMARY KEY ("test_route_id")
);

-- CreateTable
CREATE TABLE "workers" (
    "worker_id" INTEGER NOT NULL,
    "worker_name" VARCHAR(100) NOT NULL,

    CONSTRAINT "workers_pkey" PRIMARY KEY ("worker_id")
);

-- CreateIndex
CREATE INDEX "idx_customer_snapshot_customer" ON "customer_snapshots"("customer_id");

-- CreateIndex
CREATE INDEX "idx_customer_snapshot_date" ON "customer_snapshots"("snapshot_date");

-- CreateIndex
CREATE UNIQUE INDEX "customer_snapshots_daily_snapshot_date_customer_id_key" ON "customer_snapshots_daily"("snapshot_date", "customer_id");

-- CreateIndex
CREATE INDEX "idx_customer_snapshot_monthly_customer" ON "customer_snapshots_monthly"("customer_id");

-- CreateIndex
CREATE INDEX "idx_customer_snapshot_monthly_date" ON "customer_snapshots_monthly"("snapshot_date");

-- CreateIndex
CREATE INDEX "idx_customer_snapshot_quarterly_customer" ON "customer_snapshots_quarterly"("customer_id");

-- CreateIndex
CREATE INDEX "idx_customer_snapshot_quarterly_date" ON "customer_snapshots_quarterly"("snapshot_date");

-- CreateIndex
CREATE INDEX "idx_item_type_snapshot_date" ON "item_type_snapshots"("snapshot_date");

-- CreateIndex
CREATE INDEX "idx_item_type_snapshot_type" ON "item_type_snapshots"("item_type_id");

-- CreateIndex
CREATE INDEX "idx_item_type_snapshot_monthly_date" ON "item_type_snapshots_monthly"("snapshot_date");

-- CreateIndex
CREATE INDEX "idx_item_type_snapshot_monthly_type" ON "item_type_snapshots_monthly"("item_type_id");

-- CreateIndex
CREATE INDEX "idx_item_type_snapshot_quarterly_date" ON "item_type_snapshots_quarterly"("snapshot_date");

-- CreateIndex
CREATE INDEX "idx_item_type_snapshot_quarterly_type" ON "item_type_snapshots_quarterly"("item_type_id");

-- CreateIndex
CREATE INDEX "idx_kpi_snapshot_date" ON "kpi_snapshots"("snapshot_date");

-- CreateIndex
CREATE INDEX "idx_kpi_snapshot_monthly_date" ON "kpi_snapshots_monthly"("snapshot_date");

-- CreateIndex
CREATE INDEX "idx_kpi_snapshot_quarterly_date" ON "kpi_snapshots_quarterly"("snapshot_date");

-- CreateIndex
CREATE INDEX "idx_shipment_history_shipment_id" ON "shipment_history"("shipment_id");

-- CreateIndex
CREATE INDEX "idx_shipment_snapshot_customer" ON "shipment_snapshots"("customer_id");

-- CreateIndex
CREATE INDEX "idx_shipment_snapshot_date" ON "shipment_snapshots"("snapshot_date");

-- CreateIndex
CREATE INDEX "idx_shipment_snapshot_shipment" ON "shipment_snapshots"("shipment_id");

-- CreateIndex
CREATE INDEX "idx_shipment_snapshot_monthly_date" ON "shipment_snapshots_monthly"("snapshot_date");

-- CreateIndex
CREATE INDEX "idx_shipment_snapshot_monthly_shipment" ON "shipment_snapshots_monthly"("shipment_id");

-- CreateIndex
CREATE INDEX "idx_shipment_snapshot_quarterly_date" ON "shipment_snapshots_quarterly"("snapshot_date");

-- CreateIndex
CREATE INDEX "idx_shipment_snapshot_quarterly_shipment" ON "shipment_snapshots_quarterly"("shipment_id");

-- CreateIndex
CREATE INDEX "idx_sources_desc" ON "sources"("source_desc");

-- CreateIndex
CREATE INDEX "idx_station_snapshot_date" ON "station_snapshots"("snapshot_date");

-- CreateIndex
CREATE INDEX "idx_station_snapshot_station" ON "station_snapshots"("station_id");

-- CreateIndex
CREATE INDEX "idx_station_snapshot_monthly_date" ON "station_snapshots_monthly"("snapshot_date");

-- CreateIndex
CREATE INDEX "idx_station_snapshot_monthly_station" ON "station_snapshots_monthly"("station_id");

-- CreateIndex
CREATE INDEX "idx_station_snapshot_quarterly_date" ON "station_snapshots_quarterly"("snapshot_date");

-- CreateIndex
CREATE INDEX "idx_station_snapshot_quarterly_station" ON "station_snapshots_quarterly"("station_id");

-- CreateIndex
CREATE INDEX "idx_status_dist_snapshot_date" ON "status_distribution_snapshots"("snapshot_date");

-- CreateIndex
CREATE INDEX "idx_status_dist_snapshot_status" ON "status_distribution_snapshots"("status_id");

-- CreateIndex
CREATE INDEX "idx_status_dist_snapshot_monthly_date" ON "status_distribution_snapshots_monthly"("snapshot_date");

-- CreateIndex
CREATE INDEX "idx_status_dist_snapshot_monthly_status" ON "status_distribution_snapshots_monthly"("status_id");

-- CreateIndex
CREATE INDEX "idx_status_dist_snapshot_quarterly_date" ON "status_distribution_snapshots_quarterly"("snapshot_date");

-- CreateIndex
CREATE INDEX "idx_status_dist_snapshot_quarterly_status" ON "status_distribution_snapshots_quarterly"("status_id");

-- CreateIndex
CREATE UNIQUE INDEX "system_snapshots_daily_snapshot_date_key" ON "system_snapshots_daily"("snapshot_date");

-- CreateIndex
CREATE UNIQUE INDEX "system_snapshots_monthly_snapshot_date_key" ON "system_snapshots_monthly"("snapshot_date");

-- AddForeignKey
ALTER TABLE "item_routes" ADD CONSTRAINT "fk_item_routes_item_type" FOREIGN KEY ("item_type_id") REFERENCES "item_types"("item_type_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "item_routes" ADD CONSTRAINT "fk_item_routes_test_station" FOREIGN KEY ("test_station_id") REFERENCES "test_stations"("test_station_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "items" ADD CONSTRAINT "items_parent_item_id_fkey" FOREIGN KEY ("parent_item_id") REFERENCES "items"("item_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "shipment_history" ADD CONSTRAINT "shipment_history_item_type_id_fkey" FOREIGN KEY ("item_type_id") REFERENCES "item_types"("item_type_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "shipment_history" ADD CONSTRAINT "shipment_history_sending_worker_id_fkey" FOREIGN KEY ("sending_worker_id") REFERENCES "workers"("worker_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "shipment_history" ADD CONSTRAINT "shipment_history_shipment_id_fkey" FOREIGN KEY ("shipment_id") REFERENCES "shipments"("id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "shipment_items" ADD CONSTRAINT "shipment_items_item_type_id_fkey" FOREIGN KEY ("item_type_id") REFERENCES "item_types"("item_type_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "shipment_items" ADD CONSTRAINT "shipment_items_shipment_id_fkey" FOREIGN KEY ("shipment_id") REFERENCES "shipments"("id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "shipments" ADD CONSTRAINT "shipments_recieving_worker_id_fkey" FOREIGN KEY ("recieving_worker_id") REFERENCES "workers"("worker_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "shipments" ADD CONSTRAINT "shipments_sending_worker_id_fkey" FOREIGN KEY ("sending_worker_id") REFERENCES "workers"("worker_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "test_stations" ADD CONSTRAINT "fk_test_stations_test_station_type" FOREIGN KEY ("test_station_type_id") REFERENCES "test_stations_type"("test_station_type_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "testing_routes" ADD CONSTRAINT "fk_testing_routes_item_type" FOREIGN KEY ("item_type_id") REFERENCES "item_types"("item_type_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "testing_routes" ADD CONSTRAINT "fk_testing_routes_test_station_type" FOREIGN KEY ("test_station_type_id") REFERENCES "test_stations_type"("test_station_type_id") ON DELETE NO ACTION ON UPDATE NO ACTION;



-- ---------------------------------------------------------------------------
-- migration: 20260217140614_add_poc_and_stokekeeper
-- ---------------------------------------------------------------------------
-- AlterTable
ALTER TABLE "shipments" ADD COLUMN     "poc_details" VARCHAR(255);

-- AlterTable
ALTER TABLE "workers" ADD COLUMN     "stokekeeper" BOOLEAN NOT NULL DEFAULT false;


-- ---------------------------------------------------------------------------
-- migration: 20260218000000_dashboard_optimization
-- ---------------------------------------------------------------------------
-- Dashboard Optimization Migration
-- Adds: system_snapshots table, station_hourly_snapshots, station_live_counters,
--        performance indexes, materialized view, trigger-based live counters

-- ============================================================
-- 1. New Tables (from Prisma schema)
-- ============================================================

-- System snapshots table (was used in raw SQL but missing from schema)
CREATE TABLE IF NOT EXISTS "system_snapshots" (
    "snapshot_date" DATE NOT NULL,
    "total_items" INTEGER NOT NULL DEFAULT 0,
    "items_in_queue" INTEGER NOT NULL DEFAULT 0,
    "items_in_test" INTEGER NOT NULL DEFAULT 0,
    "items_finished" INTEGER NOT NULL DEFAULT 0,
    "items_waiting_for_research" INTEGER NOT NULL DEFAULT 0,
    "items_in_research" INTEGER NOT NULL DEFAULT 0,
    "items_in_routes" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "system_snapshots_pkey" PRIMARY KEY ("snapshot_date")
);

CREATE INDEX IF NOT EXISTS "idx_system_snapshot_date" ON "system_snapshots"("snapshot_date");

-- Station hourly snapshots (granular station analytics)
CREATE TABLE IF NOT EXISTS "station_hourly_snapshots" (
    "id" SERIAL NOT NULL,
    "snapshot_hour" TIMESTAMP(6) NOT NULL,
    "station_id" INTEGER NOT NULL,
    "items_processed" INTEGER NOT NULL DEFAULT 0,
    "avg_queue_time" DOUBLE PRECISION,
    "avg_test_time" DOUBLE PRECISION,
    "created_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "station_hourly_snapshots_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "station_hourly_snapshots_snapshot_hour_station_id_key" ON "station_hourly_snapshots"("snapshot_hour", "station_id");
CREATE INDEX IF NOT EXISTS "idx_station_hourly_snapshot_hour" ON "station_hourly_snapshots"("snapshot_hour");

-- Station live counters (O(1) lookups for real-time queue/test counts)
CREATE TABLE IF NOT EXISTS "station_live_counters" (
    "station_id" INTEGER NOT NULL,
    "items_in_queue" INTEGER NOT NULL DEFAULT 0,
    "items_in_test" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "station_live_counters_pkey" PRIMARY KEY ("station_id")
);

-- ============================================================
-- 2. Performance Indexes on item_routes and item_route_history
-- ============================================================

CREATE INDEX IF NOT EXISTS "idx_ir_current_status" ON "item_routes"("current_status");
CREATE INDEX IF NOT EXISTS "idx_ir_test_station_id" ON "item_routes"("test_station_id");
CREATE INDEX IF NOT EXISTS "idx_ir_finished_at" ON "item_routes"("finished_at");
CREATE INDEX IF NOT EXISTS "idx_ir_is_finished" ON "item_routes"("is_finished");

CREATE INDEX IF NOT EXISTS "idx_irh_item_id" ON "item_route_history"("item_id");
CREATE INDEX IF NOT EXISTS "idx_irh_station_id" ON "item_route_history"("test_station_id");
CREATE INDEX IF NOT EXISTS "idx_irh_processing_end_time" ON "item_route_history"("processing_end_time");
CREATE INDEX IF NOT EXISTS "idx_irh_worker_id" ON "item_route_history"("worker_id");

-- ============================================================
-- 3. Initialize Live Counters from Current Data
-- ============================================================

INSERT INTO station_live_counters (station_id, items_in_queue, items_in_test)
SELECT
    ts.test_station_id,
    COALESCE(SUM(CASE WHEN ir.current_status IN (2, 4) AND ir.is_finished = false THEN 1 ELSE 0 END), 0),
    COALESCE(SUM(CASE WHEN ir.current_status IN (1, 5) AND ir.is_finished = false THEN 1 ELSE 0 END), 0)
FROM test_stations ts
LEFT JOIN item_routes ir ON ir.test_station_id = ts.test_station_id AND ir.is_finished = false
GROUP BY ts.test_station_id
ON CONFLICT (station_id) DO UPDATE SET
    items_in_queue = EXCLUDED.items_in_queue,
    items_in_test = EXCLUDED.items_in_test;

-- ============================================================
-- 4. Trigger Function for Live Counter Updates
-- ============================================================

CREATE OR REPLACE FUNCTION update_station_counters()
RETURNS TRIGGER AS $$
BEGIN
    -- Handle INSERT
    IF (TG_OP = 'INSERT') THEN
        -- New item entering queue
        IF (NEW.current_status IN (2, 4) AND NEW.is_finished = false AND NEW.test_station_id IS NOT NULL) THEN
            INSERT INTO station_live_counters (station_id, items_in_queue, items_in_test)
            VALUES (NEW.test_station_id, 1, 0)
            ON CONFLICT (station_id) DO UPDATE
            SET items_in_queue = station_live_counters.items_in_queue + 1;
        END IF;
        -- New item entering test
        IF (NEW.current_status IN (1, 5) AND NEW.is_finished = false AND NEW.test_station_id IS NOT NULL) THEN
            INSERT INTO station_live_counters (station_id, items_in_queue, items_in_test)
            VALUES (NEW.test_station_id, 0, 1)
            ON CONFLICT (station_id) DO UPDATE
            SET items_in_test = station_live_counters.items_in_test + 1;
        END IF;
        RETURN NEW;
    END IF;

    -- Handle UPDATE
    IF (TG_OP = 'UPDATE') THEN
        -- Decrement old station counters
        IF (OLD.test_station_id IS NOT NULL) THEN
            IF (OLD.current_status IN (2, 4) AND OLD.is_finished = false) THEN
                UPDATE station_live_counters
                SET items_in_queue = GREATEST(0, items_in_queue - 1)
                WHERE station_id = OLD.test_station_id;
            END IF;
            IF (OLD.current_status IN (1, 5) AND OLD.is_finished = false) THEN
                UPDATE station_live_counters
                SET items_in_test = GREATEST(0, items_in_test - 1)
                WHERE station_id = OLD.test_station_id;
            END IF;
        END IF;

        -- Increment new station counters
        IF (NEW.test_station_id IS NOT NULL AND NEW.is_finished = false) THEN
            IF (NEW.current_status IN (2, 4)) THEN
                INSERT INTO station_live_counters (station_id, items_in_queue, items_in_test)
                VALUES (NEW.test_station_id, 1, 0)
                ON CONFLICT (station_id) DO UPDATE
                SET items_in_queue = station_live_counters.items_in_queue + 1;
            END IF;
            IF (NEW.current_status IN (1, 5)) THEN
                INSERT INTO station_live_counters (station_id, items_in_queue, items_in_test)
                VALUES (NEW.test_station_id, 0, 1)
                ON CONFLICT (station_id) DO UPDATE
                SET items_in_test = station_live_counters.items_in_test + 1;
            END IF;
        END IF;

        RETURN NEW;
    END IF;

    -- Handle DELETE
    IF (TG_OP = 'DELETE') THEN
        IF (OLD.test_station_id IS NOT NULL AND OLD.is_finished = false) THEN
            IF (OLD.current_status IN (2, 4)) THEN
                UPDATE station_live_counters
                SET items_in_queue = GREATEST(0, items_in_queue - 1)
                WHERE station_id = OLD.test_station_id;
            END IF;
            IF (OLD.current_status IN (1, 5)) THEN
                UPDATE station_live_counters
                SET items_in_test = GREATEST(0, items_in_test - 1)
                WHERE station_id = OLD.test_station_id;
            END IF;
        END IF;
        RETURN OLD;
    END IF;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- Attach trigger to item_routes
DROP TRIGGER IF EXISTS trg_update_station_counters ON item_routes;
CREATE TRIGGER trg_update_station_counters
    AFTER INSERT OR UPDATE OR DELETE ON item_routes
    FOR EACH ROW EXECUTE FUNCTION update_station_counters();

-- ============================================================
-- 5. Materialized View for Station Stats
-- ============================================================

CREATE MATERIALIZED VIEW IF NOT EXISTS mv_station_stats AS
SELECT
    irh.test_station_id,
    COUNT(*) AS processed_count,
    AVG(
        CASE WHEN irh.processing_start_time IS NOT NULL AND irh.processing_end_time IS NOT NULL
        THEN EXTRACT(EPOCH FROM (irh.processing_end_time - irh.processing_start_time)) / 60.0
        ELSE NULL END
    ) AS avg_processing_minutes,
    AVG(
        CASE WHEN irh.queue_start_time IS NOT NULL AND irh.processing_start_time IS NOT NULL
        THEN EXTRACT(EPOCH FROM (irh.processing_start_time - irh.queue_start_time)) / 60.0
        ELSE NULL END
    ) AS avg_queue_minutes
FROM item_route_history irh
WHERE irh.processing_end_time IS NOT NULL
GROUP BY irh.test_station_id;

-- Unique index required for CONCURRENTLY refresh
CREATE UNIQUE INDEX IF NOT EXISTS idx_mv_station_stats_station_id ON mv_station_stats(test_station_id);


-- ---------------------------------------------------------------------------
-- migration: 20260224085257_update_database_structure
-- ---------------------------------------------------------------------------
-- AlterTable
ALTER TABLE "items" ALTER COLUMN "serial_no" SET DATA TYPE TEXT,
ALTER COLUMN "manufacturer_no" SET DATA TYPE TEXT;


-- ---------------------------------------------------------------------------
-- migration: 20260528000000_add_file_objects
-- ---------------------------------------------------------------------------
-- CreateTable: central registry of every object stored in MinIO.
-- MinIO holds the bytes; this table is the index/audit log.
CREATE TABLE "file_objects" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "bucket" VARCHAR(255) NOT NULL,
    "object_key" VARCHAR(1024) NOT NULL,
    "file_name" VARCHAR(512) NOT NULL,
    "content_type" VARCHAR(255),
    "size_bytes" BIGINT NOT NULL DEFAULT 0,
    "checksum_sha256" VARCHAR(64),
    "entity_type" VARCHAR(64),
    "entity_id" VARCHAR(64),
    "metadata" JSONB,
    "status" VARCHAR(20) NOT NULL DEFAULT 'active',
    "created_by" VARCHAR(255),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT now(),
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "file_objects_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "file_objects_object_key_key" ON "file_objects"("object_key");

-- CreateIndex
CREATE INDEX "idx_file_objects_entity" ON "file_objects"("entity_type", "entity_id");

-- CreateIndex
CREATE INDEX "idx_file_objects_status" ON "file_objects"("status");

-- CreateIndex
CREATE INDEX "idx_file_objects_created_at" ON "file_objects"("created_at");


-- ---------------------------------------------------------------------------
-- migration: 20260604000000_add_updated_by_to_file_objects
-- ---------------------------------------------------------------------------
-- AlterTable: track who last modified each file_objects row
-- Mirrors created_by for first writes; advances on replace/edit.
ALTER TABLE "file_objects" ADD COLUMN "updated_by" VARCHAR(255);


-- ---------------------------------------------------------------------------
-- migration: 20260709084717_add_reference_items
-- ---------------------------------------------------------------------------
-- CreateTable
CREATE TABLE "reference_items" (
    "reference_item_id" SERIAL NOT NULL,
    "item_type_id" INTEGER NOT NULL,
    "manufacturer_sku" VARCHAR(255) NOT NULL,
    "manufacturer" VARCHAR(255) NOT NULL,
    "name" VARCHAR(255),
    "notes" TEXT,
    "primary_image_id" INTEGER,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "reference_items_pkey" PRIMARY KEY ("reference_item_id")
);

-- CreateTable
CREATE TABLE "reference_item_images" (
    "reference_item_image_id" SERIAL NOT NULL,
    "reference_item_id" INTEGER NOT NULL,
    "bucket" VARCHAR(255) NOT NULL,
    "object_key" VARCHAR(1024) NOT NULL,
    "file_name" VARCHAR(255) NOT NULL,
    "content_type" VARCHAR(255),
    "size_bytes" BIGINT NOT NULL DEFAULT 0,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "reference_item_images_pkey" PRIMARY KEY ("reference_item_image_id")
);

-- CreateIndex
CREATE INDEX "idx_reference_items_item_type" ON "reference_items"("item_type_id");

-- CreateIndex
CREATE INDEX "idx_reference_items_sku" ON "reference_items"("manufacturer_sku");

-- CreateIndex
CREATE UNIQUE INDEX "reference_item_images_object_key_key" ON "reference_item_images"("object_key");

-- CreateIndex
CREATE INDEX "idx_reference_item_images_item" ON "reference_item_images"("reference_item_id");

-- AddForeignKey
ALTER TABLE "reference_items" ADD CONSTRAINT "reference_items_item_type_id_fkey" FOREIGN KEY ("item_type_id") REFERENCES "item_types"("item_type_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "reference_item_images" ADD CONSTRAINT "reference_item_images_reference_item_id_fkey" FOREIGN KEY ("reference_item_id") REFERENCES "reference_items"("reference_item_id") ON DELETE CASCADE ON UPDATE CASCADE;


-- ---------------------------------------------------------------------------
-- migration: 20260712085744_add_reference_weight
-- ---------------------------------------------------------------------------
-- AlterTable
ALTER TABLE "reference_items" ADD COLUMN     "reference_weight" VARCHAR(255);


-- ---------------------------------------------------------------------------
-- migration: 20260712124950_add_test_results
-- ---------------------------------------------------------------------------
-- CreateTable
CREATE TABLE "test_results" (
    "test_result_id" SERIAL NOT NULL,
    "item_id" BIGINT NOT NULL,
    "test_station_id" INTEGER NOT NULL,
    "test_station_type_id" INTEGER NOT NULL,
    "route_number" INTEGER NOT NULL DEFAULT 1,
    "route_step" INTEGER NOT NULL,
    "worker_id" INTEGER,
    "passed" BOOLEAN,
    "result" INTEGER,
    "comments" TEXT,
    "details" JSONB,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "test_results_pkey" PRIMARY KEY ("test_result_id")
);

-- CreateIndex
CREATE INDEX "idx_test_results_item" ON "test_results"("item_id");

-- CreateIndex
CREATE INDEX "idx_test_results_station" ON "test_results"("test_station_id");

-- CreateIndex
CREATE INDEX "idx_test_results_station_type" ON "test_results"("test_station_type_id");


-- ---------------------------------------------------------------------------
-- migration: 20260713131814_add_settings_unique_constraints
-- ---------------------------------------------------------------------------
-- Unique constraints on settings-catalog name columns (prevent duplicate entries).
-- CreateIndex
CREATE UNIQUE INDEX "item_types_item_type_desc_key" ON "item_types"("item_type_desc");

-- CreateIndex
CREATE UNIQUE INDEX "item_status_item_status_desc_key" ON "item_status"("item_status_desc");

-- CreateIndex
CREATE UNIQUE INDEX "sources_source_desc_key" ON "sources"("source_desc");

-- CreateIndex
CREATE UNIQUE INDEX "test_station_status_test_station_status_desc_key" ON "test_station_status"("test_station_status_desc");

-- CreateIndex
CREATE UNIQUE INDEX "test_stations_test_station_desc_key" ON "test_stations"("test_station_desc");

-- CreateIndex
CREATE UNIQUE INDEX "test_stations_type_test_type_desc_key" ON "test_stations_type"("test_type_desc");


-- ---------------------------------------------------------------------------
-- migration: 20260719000000_add_photo_types
-- ---------------------------------------------------------------------------
-- Photo types: global classification for photos ("package", "product", ...).
-- Screens speak the stable `code`; the numeric id stays a DB-internal detail.
-- Applies to BOTH reference images (reference_item_images.photo_type_id) and
-- worker-captured item photos (file_objects.metadata.photoType — no column
-- needed there, the JSONB metadata already carries per-file tags).

-- CreateTable
CREATE TABLE "photo_types" (
    "photo_type_id" SERIAL NOT NULL,
    "code" VARCHAR(50) NOT NULL,
    "photo_type_desc" VARCHAR(255) NOT NULL,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "photo_types_pkey" PRIMARY KEY ("photo_type_id")
);

-- CreateIndex
CREATE UNIQUE INDEX "photo_types_code_key" ON "photo_types"("code");

-- Seed the initial types here (no seed script exists in this project) so every
-- environment gets identical codes even if the SERIAL ids differ.
INSERT INTO "photo_types" ("code", "photo_type_desc", "sort_order") VALUES
    ('package', 'צילום אריזה', 1),
    ('product', 'צילום פריט', 2);

-- Existing reference images predate classification (pre-production data, approved
-- for deletion). Clear the primary pointers first, then drop the rows and
-- soft-delete their file_objects registry entries. MinIO bytes are left behind
-- (versioned bucket) — acceptable for pre-production cleanup.
UPDATE "reference_items" SET "primary_image_id" = NULL;
UPDATE "file_objects"
   SET "status" = 'deleted', "deleted_at" = CURRENT_TIMESTAMP
 WHERE "entity_type" = 'reference_item_image';
DELETE FROM "reference_item_images";

-- AlterTable: every reference image must belong to a photo type.
ALTER TABLE "reference_item_images" ADD COLUMN "photo_type_id" INTEGER NOT NULL;

-- AddForeignKey (RESTRICT: a type that has images cannot be deleted)
ALTER TABLE "reference_item_images" ADD CONSTRAINT "reference_item_images_photo_type_id_fkey"
    FOREIGN KEY ("photo_type_id") REFERENCES "photo_types"("photo_type_id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- CreateIndex
CREATE INDEX "idx_reference_item_images_type" ON "reference_item_images"("photo_type_id");


-- ---------------------------------------------------------------------------
-- migration: 20260719120000_add_disassembly_assembly_photo_types
-- ---------------------------------------------------------------------------
-- Photo types for the "פירוק" (disassembly) and "הרכבה" (assembly) test
-- stations. Each single-photo station addresses its own reference-image group
-- and tags its worker captures by the stable `code` (never the SERIAL id):
--   disassembly → test_station_type_id 2
--   assembly    → test_station_type_id 5
-- Idempotent so re-running against an environment that already has them is safe.
INSERT INTO "photo_types" ("code", "photo_type_desc", "sort_order") VALUES
    ('disassembly', 'צילום פירוק', 3),
    ('assembly', 'צילום הרכבה', 4)
ON CONFLICT ("code") DO NOTHING;


-- ---------------------------------------------------------------------------
-- migration: 20260720100000_add_station_type_parents_only
-- ---------------------------------------------------------------------------
-- Station types whose stations test a parent item together with its accessories.
-- When true, the testing queue for such a station lists parent items only.
ALTER TABLE "test_stations_type"
  ADD COLUMN "parents_only" BOOLEAN NOT NULL DEFAULT false;


-- ---------------------------------------------------------------------------
-- migration: 20260727120000_add_work_hours
-- ---------------------------------------------------------------------------
-- שעות עבודה וחופשות: weekly template, single-date overrides, and the
-- department's internal-absence catalogue. National Israeli holidays are NOT
-- stored — they are computed from the Hebrew calendar at read time.

-- CreateTable
CREATE TABLE "weekday_defaults" (
    "weekday" INTEGER NOT NULL,
    "is_working" BOOLEAN NOT NULL DEFAULT true,
    "start_time" VARCHAR(5),
    "end_time" VARCHAR(5),
    "break_start" VARCHAR(5),
    "break_end" VARCHAR(5),
    "updated_by" VARCHAR(255),
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "weekday_defaults_pkey" PRIMARY KEY ("weekday")
);

-- CreateTable
CREATE TABLE "workday_overrides" (
    "id" SERIAL NOT NULL,
    "work_date" DATE NOT NULL,
    "kind" VARCHAR(20) NOT NULL,
    "start_time" VARCHAR(5),
    "end_time" VARCHAR(5),
    "break_start" VARCHAR(5),
    "break_end" VARCHAR(5),
    "note" VARCHAR(500),
    "created_by" VARCHAR(255),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "workday_overrides_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "holiday_types" (
    "id" SERIAL NOT NULL,
    "name" VARCHAR(100) NOT NULL,
    "is_system" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "holiday_types_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "department_holidays" (
    "id" SERIAL NOT NULL,
    "name" VARCHAR(200) NOT NULL,
    "type_id" INTEGER NOT NULL,
    "start_date" DATE NOT NULL,
    "end_date" DATE NOT NULL,
    "is_half_day" BOOLEAN NOT NULL DEFAULT false,
    "half_day_end_time" VARCHAR(5),
    "note" VARCHAR(500),
    "created_by" VARCHAR(255),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "department_holidays_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "workday_overrides_work_date_key" ON "workday_overrides"("work_date");

-- CreateIndex
CREATE INDEX "idx_workday_overrides_date" ON "workday_overrides"("work_date");

-- CreateIndex
CREATE UNIQUE INDEX "holiday_types_name_key" ON "holiday_types"("name");

-- CreateIndex
CREATE INDEX "idx_department_holidays_range" ON "department_holidays"("start_date", "end_date");

-- AddForeignKey
ALTER TABLE "department_holidays" ADD CONSTRAINT "department_holidays_type_id_fkey" FOREIGN KEY ("type_id") REFERENCES "holiday_types"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- ============================================================================
-- Seed — the page is empty without it. Idempotent, so re-running is safe.
-- ============================================================================

-- Weekly template: ראשון–חמישי 07:00–15:35 with a 12:00–13:00 break (net 7h35m);
-- שישי and שבת are non-working (שישי may be opened per-day via an override).
INSERT INTO "weekday_defaults" ("weekday", "is_working", "start_time", "end_time", "break_start", "break_end") VALUES
    (0, true,  '07:00', '15:35', '12:00', '13:00'),
    (1, true,  '07:00', '15:35', '12:00', '13:00'),
    (2, true,  '07:00', '15:35', '12:00', '13:00'),
    (3, true,  '07:00', '15:35', '12:00', '13:00'),
    (4, true,  '07:00', '15:35', '12:00', '13:00'),
    (5, false, NULL, NULL, NULL, NULL),
    (6, false, NULL, NULL, NULL, NULL)
ON CONFLICT ("weekday") DO NOTHING;

-- Internal-absence categories only. National חגים are automatic (library-driven),
-- so no 'חג' type is seeded here.
INSERT INTO "holiday_types" ("name", "is_system") VALUES
    ('חופשה מרוכזת', true),
    ('יום גיבוש', true),
    ('השבתה', true)
ON CONFLICT ("name") DO NOTHING;


-- ---------------------------------------------------------------------------
-- migration: 20260816103131_add_worker_name_snapshots
-- ---------------------------------------------------------------------------
-- AlterTable
ALTER TABLE "shipment_history" ADD COLUMN     "sending_worker_name" TEXT;

-- AlterTable
ALTER TABLE "shipments" ADD COLUMN     "recieving_worker_name" TEXT,
ADD COLUMN     "sending_worker_name" TEXT;


-- ---------------------------------------------------------------------------
-- migration: 20260816103434_drop_local_workers_table
-- ---------------------------------------------------------------------------
-- DropForeignKey
ALTER TABLE "shipment_history" DROP CONSTRAINT "shipment_history_sending_worker_id_fkey";

-- DropForeignKey
ALTER TABLE "shipments" DROP CONSTRAINT "shipments_recieving_worker_id_fkey";

-- DropForeignKey
ALTER TABLE "shipments" DROP CONSTRAINT "shipments_sending_worker_id_fkey";

-- DropTable
DROP TABLE "workers";


-- ---------------------------------------------------------------------------
-- migration: 20260816114251_makat_to_text
-- ---------------------------------------------------------------------------
-- AlterTable
ALTER TABLE "items" ALTER COLUMN "makat" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "shipment_history" ALTER COLUMN "makat" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "shipment_items" ALTER COLUMN "makat" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "shipments" ALTER COLUMN "makat" SET DATA TYPE TEXT;


-- ===========================================================================
-- Prisma migration bookkeeping
-- ===========================================================================
-- Marks every migration above as already applied, so a future
-- `prisma migrate deploy` run from a connected machine applies only NEW ones
-- instead of trying to re-create existing tables.
-- Guarded with NOT EXISTS, so re-running this section is harmless.

CREATE TABLE IF NOT EXISTS public._prisma_migrations (
    id                  VARCHAR(36)  PRIMARY KEY,
    checksum            VARCHAR(64)  NOT NULL,
    finished_at         TIMESTAMPTZ,
    migration_name      VARCHAR(255) NOT NULL,
    logs                TEXT,
    rolled_back_at      TIMESTAMPTZ,
    started_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    applied_steps_count INTEGER      NOT NULL DEFAULT 0
);

INSERT INTO public._prisma_migrations
       (id, checksum, finished_at, migration_name, started_at, applied_steps_count)
SELECT gen_random_uuid()::text, '7e93286860212b2e723e6353b02c8036833ad9e6ee82475b9bf9a9f4ec3c2dcc', now(), '0_init', now(), 1
WHERE NOT EXISTS (SELECT 1 FROM public._prisma_migrations WHERE migration_name = '0_init');
INSERT INTO public._prisma_migrations
       (id, checksum, finished_at, migration_name, started_at, applied_steps_count)
SELECT gen_random_uuid()::text, 'b86a2309bec8883b5b8745215af4811874a3331a62d5fa9b92f3990d5db25542', now(), '20260217140614_add_poc_and_stokekeeper', now(), 1
WHERE NOT EXISTS (SELECT 1 FROM public._prisma_migrations WHERE migration_name = '20260217140614_add_poc_and_stokekeeper');
INSERT INTO public._prisma_migrations
       (id, checksum, finished_at, migration_name, started_at, applied_steps_count)
SELECT gen_random_uuid()::text, 'e51d7ba7fcc2abcdcdecdeeb42f45873af7774145d68e30c079f5e7a29ccbfa3', now(), '20260218000000_dashboard_optimization', now(), 1
WHERE NOT EXISTS (SELECT 1 FROM public._prisma_migrations WHERE migration_name = '20260218000000_dashboard_optimization');
INSERT INTO public._prisma_migrations
       (id, checksum, finished_at, migration_name, started_at, applied_steps_count)
SELECT gen_random_uuid()::text, '5bda4bc61d33b49a0c929b01d8493f225ef333c35ae303fe7364c1a344e34c14', now(), '20260224085257_update_database_structure', now(), 1
WHERE NOT EXISTS (SELECT 1 FROM public._prisma_migrations WHERE migration_name = '20260224085257_update_database_structure');
INSERT INTO public._prisma_migrations
       (id, checksum, finished_at, migration_name, started_at, applied_steps_count)
SELECT gen_random_uuid()::text, '4fd64ec766727e98ba5325c148e0f5bba9ffb553d2cb12a2ea4475ba914b83a9', now(), '20260528000000_add_file_objects', now(), 1
WHERE NOT EXISTS (SELECT 1 FROM public._prisma_migrations WHERE migration_name = '20260528000000_add_file_objects');
INSERT INTO public._prisma_migrations
       (id, checksum, finished_at, migration_name, started_at, applied_steps_count)
SELECT gen_random_uuid()::text, '67d6229068ddf572a309e4ee4d0f4dade5e0bcd8f427c9fb071236a2bdcfda58', now(), '20260604000000_add_updated_by_to_file_objects', now(), 1
WHERE NOT EXISTS (SELECT 1 FROM public._prisma_migrations WHERE migration_name = '20260604000000_add_updated_by_to_file_objects');
INSERT INTO public._prisma_migrations
       (id, checksum, finished_at, migration_name, started_at, applied_steps_count)
SELECT gen_random_uuid()::text, '984965ff64ce090e4b4a9693b05896054aa2755ec1f91a129ddabc926ac22214', now(), '20260709084717_add_reference_items', now(), 1
WHERE NOT EXISTS (SELECT 1 FROM public._prisma_migrations WHERE migration_name = '20260709084717_add_reference_items');
INSERT INTO public._prisma_migrations
       (id, checksum, finished_at, migration_name, started_at, applied_steps_count)
SELECT gen_random_uuid()::text, 'a042b6600c184cf096bf46414cf02ccdf3de2fcfaa21e8e4d694971a024ef64d', now(), '20260712085744_add_reference_weight', now(), 1
WHERE NOT EXISTS (SELECT 1 FROM public._prisma_migrations WHERE migration_name = '20260712085744_add_reference_weight');
INSERT INTO public._prisma_migrations
       (id, checksum, finished_at, migration_name, started_at, applied_steps_count)
SELECT gen_random_uuid()::text, '85143be9c6e79b770348e658904b6cf7cd19680b08f54bfa3dfb27d2678f459d', now(), '20260712124950_add_test_results', now(), 1
WHERE NOT EXISTS (SELECT 1 FROM public._prisma_migrations WHERE migration_name = '20260712124950_add_test_results');
INSERT INTO public._prisma_migrations
       (id, checksum, finished_at, migration_name, started_at, applied_steps_count)
SELECT gen_random_uuid()::text, 'b126ca8bdc1eecebc8c1483eae7f75d74878bf87c96f295c306af690a6ebda5d', now(), '20260713131814_add_settings_unique_constraints', now(), 1
WHERE NOT EXISTS (SELECT 1 FROM public._prisma_migrations WHERE migration_name = '20260713131814_add_settings_unique_constraints');
INSERT INTO public._prisma_migrations
       (id, checksum, finished_at, migration_name, started_at, applied_steps_count)
SELECT gen_random_uuid()::text, '269033383c5b5f383f99c739d33f106dff71b66289ea788bdca3ddc567c8aa89', now(), '20260719000000_add_photo_types', now(), 1
WHERE NOT EXISTS (SELECT 1 FROM public._prisma_migrations WHERE migration_name = '20260719000000_add_photo_types');
INSERT INTO public._prisma_migrations
       (id, checksum, finished_at, migration_name, started_at, applied_steps_count)
SELECT gen_random_uuid()::text, '994f3517b78704e9cd382e1fbf4bd7d7c02b220398ba7a79262378c8916a83cb', now(), '20260719120000_add_disassembly_assembly_photo_types', now(), 1
WHERE NOT EXISTS (SELECT 1 FROM public._prisma_migrations WHERE migration_name = '20260719120000_add_disassembly_assembly_photo_types');
INSERT INTO public._prisma_migrations
       (id, checksum, finished_at, migration_name, started_at, applied_steps_count)
SELECT gen_random_uuid()::text, '97781e7899dc56702c8defe52a75032bcca2ed3e4c1144c2af5bbcbc98cf022c', now(), '20260720100000_add_station_type_parents_only', now(), 1
WHERE NOT EXISTS (SELECT 1 FROM public._prisma_migrations WHERE migration_name = '20260720100000_add_station_type_parents_only');
INSERT INTO public._prisma_migrations
       (id, checksum, finished_at, migration_name, started_at, applied_steps_count)
SELECT gen_random_uuid()::text, 'd13c39f6dc0ec9525209870657c94084208de24743cddc77a5e443a8c1be6c54', now(), '20260727120000_add_work_hours', now(), 1
WHERE NOT EXISTS (SELECT 1 FROM public._prisma_migrations WHERE migration_name = '20260727120000_add_work_hours');
INSERT INTO public._prisma_migrations
       (id, checksum, finished_at, migration_name, started_at, applied_steps_count)
SELECT gen_random_uuid()::text, '1c8f7bf35a93b5623e959e43980bc5ad35318de2436c028d72f545f59940eb5f', now(), '20260816103131_add_worker_name_snapshots', now(), 1
WHERE NOT EXISTS (SELECT 1 FROM public._prisma_migrations WHERE migration_name = '20260816103131_add_worker_name_snapshots');
INSERT INTO public._prisma_migrations
       (id, checksum, finished_at, migration_name, started_at, applied_steps_count)
SELECT gen_random_uuid()::text, '8e50068c771164ff72bb4fe4783ed75b82c85193028ad0af39ba6d66e9d7f6d9', now(), '20260816103434_drop_local_workers_table', now(), 1
WHERE NOT EXISTS (SELECT 1 FROM public._prisma_migrations WHERE migration_name = '20260816103434_drop_local_workers_table');
INSERT INTO public._prisma_migrations
       (id, checksum, finished_at, migration_name, started_at, applied_steps_count)
SELECT gen_random_uuid()::text, '42324749850738357abdbdbcf3543a695398f1d9b7f58b131e7809f85cb4edf3', now(), '20260816114251_makat_to_text', now(), 1
WHERE NOT EXISTS (SELECT 1 FROM public._prisma_migrations WHERE migration_name = '20260816114251_makat_to_text');
